language: php

php:
    - 5.2
    - 5.3
    - 5.4
    - 5.5

before_install:
    - phpize
    - ./configure --enable-stem

script:
    - export NO_INTERACTION=1
    - make test

notifications:
    email: false
